-- =====================================================
-- 04. POPULATE EXPERTS TABLE
-- =====================================================
-- Experts are CS consultants who provide expert help to clients
-- Must be inserted AFTER Users table is populated

INSERT INTO "Experts" (
  expert_id, user_id, name, email, department, title,
  years_experience, expert_level, location, timezone,
  primary_expertise, secondary_expertise, bio,
  is_active, is_available, created_at, updated_at
) VALUES
(
  'EXP-001',
  (SELECT user_id FROM "Users" WHERE email = 'rachel.thompson@scalepoint.com'),
  'Rachel Thompson',
  'rachel.thompson@scalepoint.com',
  'Customer Success',
  'Principal Customer Success Manager',
  12,
  'senior',
  'San Francisco, CA',
  'America/Los_Angeles',
  'Enterprise Implementation & Onboarding',
  'Healthcare & Life Sciences',
  'Led 200+ enterprise implementations across healthcare sector. Created ScalePoint''s enterprise onboarding methodology. Former consultant at Deloitte specializing in healthcare digital transformation.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-002',
  (SELECT user_id FROM "Users" WHERE email = 'michael.chen@scalepoint.com'),
  'Michael Chen',
  'michael.chen@scalepoint.com',
  'Customer Success',
  'Senior Director of Customer Success Operations',
  15,
  'senior',
  'New York, NY',
  'America/New_York',
  'Financial Services & Banking',
  'Regulatory Compliance & Security',
  '15 years in financial services technology. Former VP at JPMorgan Chase leading digital customer experience. Expert in SOX, PCI-DSS, and banking regulations. Built compliance frameworks used across ScalePoint''s financial clients.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-003',
  (SELECT user_id FROM "Users" WHERE email = 'sarah.martinez@scalepoint.com'),
  'Sarah Martinez',
  'sarah.martinez@scalepoint.com',
  'Customer Success',
  'Customer Success Enablement Manager',
  10,
  'expert',
  'Austin, TX',
  'America/Chicago',
  'Training & Education Programs',
  'Mid-Market Customer Success',
  'Designed ScalePoint''s customer education curriculum. Former head of training at Salesforce. Created certification programs used by 1000+ customers. Expert in adult learning methodologies and customer adoption strategies.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-004',
  (SELECT user_id FROM "Users" WHERE email = 'david.kim@scalepoint.com'),
  'David Kim',
  'david.kim@scalepoint.com',
  'Customer Success',
  'Senior Customer Success Manager - Manufacturing',
  11,
  'expert',
  'Chicago, IL',
  'America/Chicago',
  'Manufacturing & Supply Chain',
  'IoT Integrations & Data Analytics',
  'Former operations manager at Ford Motor Company. Led digital transformation initiatives for 50+ manufacturing clients. Deep expertise in lean manufacturing, Six Sigma, and industrial IoT integrations with ScalePoint platform.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-005',
  (SELECT user_id FROM "Users" WHERE email = 'jennifer.walsh@scalepoint.com'),
  'Jennifer Walsh',
  'jennifer.walsh@scalepoint.com',
  'Customer Success',
  'Global Customer Success Manager - SMB',
  8,
  'expert',
  'Denver, CO',
  'America/Denver',
  'SMB Customer Success at Scale',
  'Automation & Self-Service',
  'Built ScalePoint''s high-velocity SMB success program. Former customer success manager at HubSpot managing 500+ SMB accounts. Expert in automation workflows, self-service methodologies, and scalable customer success operations.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-006',
  (SELECT user_id FROM "Users" WHERE email = 'alex.rodriguez@scalepoint.com'),
  'Alex Rodriguez',
  'alex.rodriguez@scalepoint.com',
  'Product Management',
  'VP of Product Management',
  14,
  'senior',
  'San Francisco, CA',
  'America/Los_Angeles',
  'AI & Machine Learning Features',
  'Product Strategy & Roadmap',
  'Led AI/ML product development at Google for 8 years. Architected ScalePoint''s predictive analytics and FUSE health scoring system. PhD in Machine Learning from Stanford. Holds 12 patents in predictive customer analytics.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-007',
  (SELECT user_id FROM "Users" WHERE email = 'maria.gonzalez@scalepoint.com'),
  'Maria Gonzalez',
  'maria.gonzalez@scalepoint.com',
  'Product Management',
  'Senior Product Manager - Integrations',
  9,
  'expert',
  'Seattle, WA',
  'America/Los_Angeles',
  'API Architecture & Third-Party Integrations',
  'Enterprise Software Ecosystem',
  'Former integration architect at Salesforce and Microsoft. Built ScalePoint''s integration marketplace with 200+ pre-built connectors. Expert in REST APIs, webhooks, and enterprise software architecture patterns.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-008',
  (SELECT user_id FROM "Users" WHERE email = 'robert.johnson@scalepoint.com'),
  'Robert Johnson',
  'robert.johnson@scalepoint.com',
  'Product Management',
  'Principal Product Manager - Analytics',
  12,
  'senior',
  'Boston, MA',
  'America/New_York',
  'Business Intelligence & Reporting',
  'Data Visualization & Dashboards',
  'Former senior product manager at Tableau. Built ScalePoint''s advanced analytics and executive dashboard suite. Expert in data visualization, self-service BI, and executive reporting for customer success metrics.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-009',
  (SELECT user_id FROM "Users" WHERE email = 'lisa.park@scalepoint.com'),
  'Lisa Park',
  'lisa.park@scalepoint.com',
  'Product Management',
  'Senior Product Manager - Mobile & User Experience',
  10,
  'expert',
  'San Diego, CA',
  'America/Los_Angeles',
  'Mobile Applications & UX Design',
  'User Research & Design Thinking',
  'Former UX director at Uber and Airbnb. Led ScalePoint''s mobile-first customer success initiatives. Expert in mobile UX patterns, accessibility, and user research methodologies. Certified Design Thinking facilitator.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-010',
  (SELECT user_id FROM "Users" WHERE email = 'james.wilson@scalepoint.com'),
  'James Wilson',
  'james.wilson@scalepoint.com',
  'Product Management',
  'Product Manager - Security & Compliance',
  11,
  'expert',
  'Atlanta, GA',
  'America/New_York',
  'Enterprise Security & Data Privacy',
  'GDPR, SOC 2, and Compliance Frameworks',
  'Former cybersecurity consultant at PwC. Built ScalePoint''s security and compliance infrastructure. Expert in GDPR, SOC 2, HIPAA, and enterprise security frameworks. Certified Information Systems Security Professional (CISSP).',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-011',
  (SELECT user_id FROM "Users" WHERE email = 'thomas.anderson@scalepoint.com'),
  'Thomas Anderson',
  'thomas.anderson@scalepoint.com',
  'Sales',
  'VP of Enterprise Sales',
  16,
  'senior',
  'New York, NY',
  'America/New_York',
  'Enterprise Sales Strategy & C-Level Selling',
  'Financial Services & Healthcare Sales',
  'Built enterprise sales teams at Oracle and Salesforce. Closed $100M+ in enterprise deals. Expert in complex enterprise sales cycles, C-level relationship building, and strategic account planning. Teaches enterprise selling at UC Berkeley.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-012',
  (SELECT user_id FROM "Users" WHERE email = 'amanda.foster.sales@scalepoint.com'),
  'Amanda Foster',
  'amanda.foster.sales@scalepoint.com',
  'Sales',
  'Regional Sales Director - West',
  12,
  'senior',
  'San Francisco, CA',
  'America/Los_Angeles',
  'Technology Sector Sales',
  'Competitive Intelligence & Market Analysis',
  'Former regional sales director at HubSpot and Zendesk. Deep knowledge of customer success software competitive landscape. Expert in technology sector buying patterns and ROI justification for CS platforms.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-013',
  (SELECT user_id FROM "Users" WHERE email = 'kevin.martinez.sales@scalepoint.com'),
  'Kevin Martinez',
  'kevin.martinez.sales@scalepoint.com',
  'Sales',
  'Senior Account Executive - Manufacturing',
  10,
  'expert',
  'Detroit, MI',
  'America/Detroit',
  'Manufacturing & Industrial Sales',
  'Value-Based Selling & ROI Modeling',
  'Former sales manager at GE Digital. Specialized in selling technology solutions to manufacturing companies. Expert in industrial sector business processes, operational efficiency metrics, and manufacturing-specific ROI calculations.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-014',
  (SELECT user_id FROM "Users" WHERE email = 'rachel.brown@scalepoint.com'),
  'Rachel Brown',
  'rachel.brown@scalepoint.com',
  'Sales',
  'Sales Manager - Mid-Market',
  8,
  'expert',
  'Austin, TX',
  'America/Chicago',
  'Mid-Market Sales Acceleration',
  'SaaS Metrics & Customer Success ROI',
  'Former sales team lead at Gainsight and ChurnZero. Expert in mid-market customer success software sales. Deep understanding of SaaS metrics, customer success ROI calculations, and mid-market buying processes.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-015',
  (SELECT user_id FROM "Users" WHERE email = 'daniel.lee@scalepoint.com'),
  'Daniel Lee',
  'daniel.lee@scalepoint.com',
  'Sales',
  'Account Executive - SMB & Growth',
  7,
  'specialist',
  'Phoenix, AZ',
  'America/Phoenix',
  'SMB & High-Velocity Sales',
  'Sales Technology & Automation',
  'Former inside sales manager at Zoom and Slack. Built high-velocity sales processes for SMB segment. Expert in sales automation, lead qualification, and SMB customer success solution positioning.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-016',
  (SELECT user_id FROM "Users" WHERE email = 'brian.thompson@scalepoint.com'),
  'Brian Thompson',
  'brian.thompson@scalepoint.com',
  'Pre-Sales/Solutions Engineering',
  'Principal Solutions Architect',
  14,
  'senior',
  'Boston, MA',
  'America/New_York',
  'Enterprise Architecture & Technical Implementation',
  'Cloud Infrastructure & Scalability',
  'Former solutions architect at AWS and Microsoft. Designed technical architectures for 100+ enterprise ScalePoint implementations. Expert in cloud infrastructure, API architecture, and enterprise software integration patterns.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-017',
  (SELECT user_id FROM "Users" WHERE email = 'carol.davis@scalepoint.com'),
  'Carol Davis',
  'carol.davis@scalepoint.com',
  'Pre-Sales/Solutions Engineering',
  'Senior Solutions Engineer - Healthcare',
  11,
  'expert',
  'Chicago, IL',
  'America/Chicago',
  'Healthcare IT & HIPAA Compliance',
  'Data Security & Privacy',
  'Former IT director at Mayo Clinic. Expert in healthcare IT systems, HIPAA compliance, and medical data security. Led technical evaluations for 50+ healthcare ScalePoint implementations.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-018',
  (SELECT user_id FROM "Users" WHERE email = 'steven.garcia@scalepoint.com'),
  'Steven Garcia',
  'steven.garcia@scalepoint.com',
  'Pre-Sales/Solutions Engineering',
  'Solutions Engineer - Financial Services',
  9,
  'expert',
  'New York, NY',
  'America/New_York',
  'Financial Services Technology',
  'Banking APIs & Fintech Integrations',
  'Former technology consultant at Goldman Sachs. Expert in financial services technology stacks, banking APIs, and fintech integration patterns. Deep knowledge of financial regulatory requirements and data governance.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-019',
  (SELECT user_id FROM "Users" WHERE email = 'michelle.rodriguez@scalepoint.com'),
  'Michelle Rodriguez',
  'michelle.rodriguez@scalepoint.com',
  'Pre-Sales/Solutions Engineering',
  'Senior Solutions Engineer - Integrations',
  10,
  'expert',
  'Seattle, WA',
  'America/Los_Angeles',
  'CRM & Marketing Automation Integrations',
  'Data Migration & ETL Processes',
  'Former integration specialist at Salesforce and Marketo. Built 200+ CRM and marketing automation integrations. Expert in data mapping, ETL processes, and customer data platform architecture.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-020',
  (SELECT user_id FROM "Users" WHERE email = 'christopher.lee@scalepoint.com'),
  'Christopher Lee',
  'christopher.lee@scalepoint.com',
  'Pre-Sales/Solutions Engineering',
  'Solutions Engineer - SMB & Self-Service',
  7,
  'specialist',
  'Denver, CO',
  'America/Denver',
  'Self-Service Implementation & Automation',
  'SMB Technical Requirements',
  'Former implementation manager at Zendesk and Freshworks. Expert in self-service customer success implementations, SMB technical requirements, and automated onboarding workflows.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-021',
  (SELECT user_id FROM "Users" WHERE email = 'jessica.wilson@scalepoint.com'),
  'Jessica Wilson',
  'jessica.wilson@scalepoint.com',
  'Marketing',
  'VP of Product Marketing',
  13,
  'senior',
  'San Francisco, CA',
  'America/Los_Angeles',
  'Customer Success Industry Thought Leadership',
  'Competitive Intelligence & Market Positioning',
  'Former product marketing director at Gainsight. Recognized industry thought leader in customer success. Authored ''The Customer Success Playbook'' (bestseller). Regular speaker at CS conferences. Deep competitive intelligence on CS software market.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-022',
  (SELECT user_id FROM "Users" WHERE email = 'mark.johnson@scalepoint.com'),
  'Mark Johnson',
  'mark.johnson@scalepoint.com',
  'Marketing',
  'Senior Content Marketing Manager',
  9,
  'expert',
  'Austin, TX',
  'America/Chicago',
  'Customer Success Content & Education',
  'Industry Best Practices & Case Studies',
  'Created ScalePoint''s customer success content library with 500+ resources. Former content manager at HubSpot Academy. Expert in customer success best practices, methodology frameworks, and educational content creation.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-023',
  (SELECT user_id FROM "Users" WHERE email = 'laura.martinez@scalepoint.com'),
  'Laura Martinez',
  'laura.martinez@scalepoint.com',
  'Marketing',
  'Industry Marketing Manager - Enterprise',
  10,
  'expert',
  'New York, NY',
  'America/New_York',
  'Enterprise Market Intelligence',
  'Industry Vertical Marketing',
  'Former market research analyst at Forrester Research covering enterprise software. Deep expertise in enterprise buying patterns, industry trends, and vertical market analysis. Published 50+ research reports on customer success market.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-024',
  (SELECT user_id FROM "Users" WHERE email = 'ryan.davis@scalepoint.com'),
  'Ryan Davis',
  'ryan.davis@scalepoint.com',
  'Marketing',
  'Competitive Intelligence Manager',
  8,
  'expert',
  'Seattle, WA',
  'America/Los_Angeles',
  'Customer Success Software Competitive Analysis',
  'Feature Comparison & Differentiation',
  'Former product marketing manager at Zendesk and Freshworks. Maintains comprehensive competitive intelligence on 20+ CS software vendors. Expert in feature differentiation, pricing analysis, and competitive positioning strategies.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-025',
  (SELECT user_id FROM "Users" WHERE email = 'emily.chen@scalepoint.com'),
  'Emily Chen',
  'emily.chen@scalepoint.com',
  'Marketing',
  'Customer Marketing Manager',
  7,
  'specialist',
  'San Diego, CA',
  'America/Los_Angeles',
  'Customer Success Stories & Case Studies',
  'Customer Advocacy & Reference Programs',
  'Built ScalePoint''s customer advocacy program from zero to 200+ active references. Former customer marketing manager at Slack. Expert in customer success story development, case study creation, and reference program management.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-026',
  (SELECT user_id FROM "Users" WHERE email = 'andrew.miller@scalepoint.com'),
  'Andrew Miller',
  'andrew.miller@scalepoint.com',
  'Engineering/Development',
  'Principal Software Engineer - Platform',
  15,
  'senior',
  'San Francisco, CA',
  'America/Los_Angeles',
  'Core Platform Architecture & Performance',
  'Scalability & System Optimization',
  'Lead architect of ScalePoint''s core platform. Former principal engineer at Netflix and Uber. Expert in distributed systems, microservices architecture, and platform scalability. Built systems handling 10M+ customer interactions daily.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-027',
  (SELECT user_id FROM "Users" WHERE email = 'sarah.kim@scalepoint.com'),
  'Sarah Kim',
  'sarah.kim@scalepoint.com',
  'Engineering/Development',
  'Senior Software Engineer - AI/ML',
  10,
  'expert',
  'Seattle, WA',
  'America/Los_Angeles',
  'Machine Learning & Predictive Analytics',
  'Natural Language Processing & AI',
  'Built ScalePoint''s AI-powered FUSE health scoring and churn prediction models. Former ML engineer at Google and Amazon. PhD in Computer Science from MIT. Expert in customer analytics ML models and NLP for customer feedback analysis.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-028',
  (SELECT user_id FROM "Users" WHERE email = 'michael.wang@scalepoint.com'),
  'Michael Wang',
  'michael.wang@scalepoint.com',
  'Engineering/Development',
  'Staff Engineer - Integrations & APIs',
  12,
  'senior',
  'Austin, TX',
  'America/Chicago',
  'API Architecture & Third-Party Integrations',
  'Webhook Systems & Real-Time Data Processing',
  'Architected ScalePoint''s integration platform supporting 200+ third-party connectors. Former integration engineer at Salesforce and Zapier. Expert in REST APIs, GraphQL, webhook systems, and real-time data processing architectures.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-029',
  (SELECT user_id FROM "Users" WHERE email = 'jennifer.taylor@scalepoint.com'),
  'Jennifer Taylor',
  'jennifer.taylor@scalepoint.com',
  'Engineering/Development',
  'Senior DevOps Engineer',
  11,
  'expert',
  'Denver, CO',
  'America/Denver',
  'Cloud Infrastructure & Deployment',
  'Security & Compliance Automation',
  'Built ScalePoint''s cloud infrastructure on AWS supporting 99.99% uptime. Former DevOps engineer at Atlassian and GitHub. Expert in Kubernetes, CI/CD pipelines, infrastructure as code, and automated security compliance.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
),
(
  'EXP-030',
  (SELECT user_id FROM "Users" WHERE email = 'robert.chen@scalepoint.com'),
  'Robert Chen',
  'robert.chen@scalepoint.com',
  'Engineering/Development',
  'Senior Frontend Engineer - User Experience',
  9,
  'expert',
  'Boston, MA',
  'America/New_York',
  'Frontend Architecture & User Interface',
  'Mobile Development & Progressive Web Apps',
  'Lead frontend engineer for ScalePoint''s customer success platform UI. Former senior engineer at Airbnb and Stripe. Expert in React, Vue.js, mobile-first design, and progressive web app development. Built interfaces used by 100K+ customer success professionals daily.',
  true,
  true,
  '2025-10-25 20:00:00+00',
  '2025-10-25 20:00:00+00'
);

-- Verification
SELECT e.expert_id, e.name, e.email, e.expert_level, e.primary_expertise
FROM "Experts" e
ORDER BY e.expert_id;

